from __future__ import annotations

import argparse
import hashlib
import os
from pathlib import Path
import stat

import pytest
from apparatus_core import shims
import apparatus_core.render as render_module
from apparatus_core.check import check_workspace
from apparatus_core.commands import render as render_command
from apparatus_core.render import RenderError, RenderResult, render_workspace, rendered_shims
from apparatus_core.shims import SHIM_REGISTRY


def _workspace(path: Path, canon: bytes = b"# Workspace canon\n") -> Path:
    path.mkdir()
    (path / "AGENTS.md").write_bytes(canon)
    return path


def _checked_workspace(path: Path) -> Path:
    workspace = _workspace(path)
    (workspace / "Welcome.md").write_text("Welcome\n", encoding="utf-8")
    for relative in (
        "Goals",
        "Decisions",
        "Projects",
        "Library",
        "Deliverables",
        "Memory/People",
        "Memory/Facts",
        "System",
    ):
        (workspace / relative).mkdir(parents=True, exist_ok=True)
    return workspace


def _tree_state(root: Path) -> tuple[tuple[str, str, bytes | str | None], ...]:
    entries: list[tuple[str, str, bytes | str | None]] = []
    for path in sorted(root.rglob("*")):
        relative = path.relative_to(root).as_posix()
        if path.is_symlink():
            entries.append((relative, "symlink", os.readlink(path)))
        elif path.is_file():
            entries.append((relative, "file", path.read_bytes()))
        else:
            entries.append((relative, "directory", None))
    return tuple(entries)


def test_render_is_deterministic_and_uses_raw_canon_bytes(tmp_path):
    canon = b"# Workspace canon\r\n\xff\n"
    workspace = _workspace(tmp_path / "workspace", canon)
    first = render_workspace(workspace)
    first_bytes = {shim.target: (workspace / shim.target).read_bytes() for shim in rendered_shims(workspace)}
    second = render_workspace(workspace)

    digest = hashlib.sha256(canon).hexdigest()
    assert set(first.written) == {target for target, _ in SHIM_REGISTRY}
    assert second.written == ()
    assert set(second.unchanged) == {target for target, _ in SHIM_REGISTRY}
    for target, content in first_bytes.items():
        assert digest.encode() in content
        assert b"Generated by apparatus render. Do not edit by hand." in content
        assert b"Edit AGENTS.md, then run apparatus render." in content


def test_cursor_header_is_a_yaml_comment_inside_valid_frontmatter(tmp_path):
    workspace = _workspace(tmp_path / "workspace")
    render_workspace(workspace)
    cursor = (workspace / ".cursor/rules/apparatus.mdc").read_text(encoding="utf-8")
    frontmatter, _body = cursor.split("---\n", 2)[1:]
    assert frontmatter.startswith("# Generated by apparatus render")
    assert "alwaysApply: true\n" in frontmatter


def test_render_command_exit_contract_and_status_lines(tmp_path, capsys):
    missing = tmp_path / "missing"
    assert render_command.run(argparse.Namespace(workspace=str(missing))) == 2
    assert "workspace path does not exist" in capsys.readouterr().out

    file_path = tmp_path / "file"
    file_path.write_text("x", encoding="utf-8")
    assert render_command.run(argparse.Namespace(workspace=str(file_path))) == 2
    assert "workspace path is not a directory" in capsys.readouterr().out

    workspace = _workspace(tmp_path / "workspace")
    assert render_command.run(argparse.Namespace(workspace=str(workspace))) == 0
    output = capsys.readouterr().out
    assert output.count("written ") == len(SHIM_REGISTRY)
    assert render_command.run(argparse.Namespace(workspace=str(workspace))) == 0
    assert capsys.readouterr().out.count("unchanged ") == len(SHIM_REGISTRY)

    no_canon = tmp_path / "no-canon"
    no_canon.mkdir()
    assert render_command.run(argparse.Namespace(workspace=str(no_canon))) == 2
    assert "missing AGENTS.md" in capsys.readouterr().out


def test_render_rejects_a_symlinked_canon(tmp_path):
    workspace = tmp_path / "workspace"
    workspace.mkdir()
    outside = tmp_path / "outside-agents.md"
    outside.write_text("# Outside canon\n", encoding="utf-8")
    (workspace / "AGENTS.md").symlink_to(outside)

    assert render_command.run(argparse.Namespace(workspace=str(workspace))) == 2
    assert outside.read_text(encoding="utf-8") == "# Outside canon\n"


def test_reparse_detector_recognizes_windows_junction_attributes(monkeypatch):
    class JunctionStatus:
        st_mode = stat.S_IFDIR
        st_file_attributes = 0x400

    monkeypatch.setattr(render_module.os, "lstat", lambda _path: JunctionStatus())
    assert render_module.is_reparse_path(Path("junction"))


def test_render_and_check_honor_an_injected_synthetic_registry(tmp_path):
    workspace = _checked_workspace(tmp_path / "workspace")
    registry = (("Synthetic.md", "claude-md.template"),)
    assert render_workspace(workspace, registry=registry).written == ("Synthetic.md",)
    assert check_workspace(workspace, shim_registry=registry).ok
    (workspace / "Synthetic.md").write_text("hand edit\n", encoding="utf-8")
    findings = check_workspace(workspace, shim_registry=registry).findings
    assert [(finding.code, finding.path) for finding in findings] == [("shim-drift", "Synthetic.md")]
    assert "apparatus render" in findings[0].hint


def test_default_render_and_check_read_the_live_registry(monkeypatch, tmp_path):
    workspace = _checked_workspace(tmp_path / "workspace")
    registry = (("Synthetic.md", "claude-md.template"),)
    monkeypatch.setattr(shims, "SHIM_REGISTRY", registry)

    assert render_workspace(workspace).written == ("Synthetic.md",)
    assert check_workspace(workspace).ok
    (workspace / "Synthetic.md").write_text("hand edit\n", encoding="utf-8")
    assert [(finding.code, finding.path) for finding in check_workspace(workspace).findings] == [
        ("shim-drift", "Synthetic.md")
    ]


def test_render_check_drift_loop_and_missing_hint(tmp_path):
    workspace = _checked_workspace(tmp_path / "workspace")
    before = check_workspace(workspace)
    assert {finding.code for finding in before.findings} == {"shim-missing"}
    assert all("apparatus render" in finding.hint for finding in before.findings)

    render_workspace(workspace)
    assert check_workspace(workspace).ok
    (workspace / "AGENTS.md").write_text("# Changed canon\n", encoding="utf-8")
    stale = check_workspace(workspace).findings
    assert [(finding.code, finding.path) for finding in stale] == [
        ("shim-drift", target) for target, _ in SHIM_REGISTRY
    ]
    render_workspace(workspace)
    assert check_workspace(workspace).ok


def test_missing_canon_marks_present_shims_as_drift_without_reading_symlinks(tmp_path):
    workspace = _checked_workspace(tmp_path / "workspace")
    render_workspace(workspace)
    outside = tmp_path / "outside.md"
    outside.write_text("outside sentinel\n", encoding="utf-8")
    (workspace / "AGENTS.md").unlink()
    (workspace / "CLAUDE.md").unlink()
    (workspace / "CLAUDE.md").symlink_to(outside)

    findings = check_workspace(workspace).findings
    assert [(finding.code, finding.path) for finding in findings] == [
        ("shim-drift", "CLAUDE.md"),
        ("shim-drift", ".cursor/rules/apparatus.mdc"),
        ("shim-drift", ".github/copilot-instructions.md"),
    ]
    assert outside.read_text(encoding="utf-8") == "outside sentinel\n"


def test_unusable_canon_keeps_absent_targets_missing_and_present_targets_drift(tmp_path):
    workspace = _checked_workspace(tmp_path / "workspace")
    outside = tmp_path / "outside-agents.md"
    outside.write_text("# Outside canon\n", encoding="utf-8")
    (workspace / "AGENTS.md").unlink()
    (workspace / "AGENTS.md").symlink_to(outside)
    (workspace / "CLAUDE.md").write_text("stale shim\n", encoding="utf-8")

    assert [(finding.code, finding.path) for finding in check_workspace(workspace).findings] == [
        ("shim-drift", "CLAUDE.md"),
        ("shim-missing", ".cursor/rules/apparatus.mdc"),
        ("shim-missing", ".github/copilot-instructions.md"),
    ]
    assert outside.read_text(encoding="utf-8") == "# Outside canon\n"


def test_render_rejects_a_symlinked_shim_target(tmp_path):
    workspace = _workspace(tmp_path / "workspace")
    outside = tmp_path / "outside.md"
    outside.write_text("outside sentinel\n", encoding="utf-8")
    (workspace / "CLAUDE.md").symlink_to(outside)

    result = render_command.run(argparse.Namespace(workspace=str(workspace)))
    assert result == 2
    assert outside.read_text(encoding="utf-8") == "outside sentinel\n"


def test_render_rejects_a_symlinked_workspace_without_touching_the_referent(tmp_path):
    referent = _workspace(tmp_path / "referent")
    (referent / "sentinel.txt").write_text("keep\n", encoding="utf-8")
    workspace = tmp_path / "workspace-link"
    workspace.symlink_to(referent, target_is_directory=True)
    before = _tree_state(referent)

    assert render_command.run(argparse.Namespace(workspace=str(workspace))) == 2
    assert _tree_state(referent) == before


def test_render_preflights_later_collision_before_touching_earlier_targets(tmp_path):
    workspace = _workspace(tmp_path / "workspace")
    blocked = workspace / "blocked"
    blocked.write_bytes(b"sentinel")
    before = _tree_state(workspace)
    registry = (("earlier.md", "claude-md.template"), ("blocked/child.md", "claude-md.template"))

    assert render_command.run(
        argparse.Namespace(workspace=str(workspace)),
        engine=lambda root: render_workspace(root, registry=registry),
    ) == 2
    assert _tree_state(workspace) == before


@pytest.mark.parametrize(
    "target",
    (
        "C:/shim.md",
        "C:shim.md",
        r"\\server\share\shim.md",
        r"nested\shim.md",
        "AGENTS.md.",
        "AGENTS.md ",
        "CON.md",
        "LPT9.txt",
        "name:stream",
        "bad?.md",
        "bad\x01.md",
    ),
)
def test_render_rejects_nonportable_registry_targets_without_mutation(tmp_path, target):
    workspace = _workspace(tmp_path / "workspace")
    before = _tree_state(workspace)

    with pytest.raises(RenderError):
        render_workspace(workspace, registry=((target, "claude-md.template"),))
    assert _tree_state(workspace) == before


@pytest.mark.parametrize(
    "registry",
    (
        (("AGENTS.md", "claude-md.template"),),
        (("agents.md", "claude-md.template"),),
        (("same.md", "claude-md.template"), ("same.md", "claude-md.template")),
        (("Same.md", "claude-md.template"), ("same.md", "claude-md.template")),
        (("nested", "claude-md.template"), ("nested/shim.md", "claude-md.template")),
        (("Nested", "claude-md.template"), ("nested/shim.md", "claude-md.template")),
        (("café.md", "claude-md.template"), ("cafe\u0301.md", "claude-md.template")),
    ),
)
def test_render_rejects_conflicting_registry_targets_before_mutation(tmp_path, registry):
    workspace = _workspace(tmp_path / "workspace")
    before = _tree_state(workspace)

    with pytest.raises(RenderError):
        render_workspace(workspace, registry=registry)
    assert _tree_state(workspace) == before


def test_render_replaces_a_workspace_hardlink_without_mutating_its_other_name(tmp_path):
    workspace = _workspace(tmp_path / "workspace")
    outside = tmp_path / "outside.md"
    outside.write_bytes(b"outside sentinel")
    target = workspace / "CLAUDE.md"
    os.link(outside, target)
    outside_before = os.stat(outside)
    registry = (("CLAUDE.md", "claude-md.template"),)

    assert render_workspace(workspace, registry=registry).written == ("CLAUDE.md",)
    assert outside.read_bytes() == b"outside sentinel"
    assert os.stat(outside).st_ino == outside_before.st_ino
    assert os.stat(target).st_ino != outside_before.st_ino
    assert target.read_bytes() == rendered_shims(workspace, registry=registry)[0].content


def test_render_does_not_publish_a_substituted_temporary_file(monkeypatch, tmp_path):
    workspace = _workspace(tmp_path / "workspace")
    target = workspace / "CLAUDE.md"
    target.write_bytes(b"target sentinel")
    registry = (("CLAUDE.md", "claude-md.template"),)

    def substitute(temporary, _identity, _content):
        temporary.unlink()
        temporary.write_bytes(b"substituted")
        return False

    monkeypatch.setattr(render_module, "_temporary_matches", substitute)
    with pytest.raises(RenderError):
        render_workspace(workspace, registry=registry)
    assert target.read_bytes() == b"target sentinel"
    assert [path.read_bytes() for path in workspace.glob(".apparatus-render-*.tmp")] == [
        b"substituted"
    ]


def test_render_cleans_up_an_owned_temporary_after_replace_failure(monkeypatch, tmp_path):
    workspace = _workspace(tmp_path / "workspace")
    target = workspace / "CLAUDE.md"
    target.write_bytes(b"target sentinel")
    registry = (("CLAUDE.md", "claude-md.template"),)
    monkeypatch.setattr(
        render_module.os,
        "replace",
        lambda _temporary, _target: (_ for _ in ()).throw(OSError("replace failed")),
    )

    with pytest.raises(RenderError):
        render_workspace(workspace, registry=registry)
    assert target.read_bytes() == b"target sentinel"
    assert not list(workspace.glob(".apparatus-render-*.tmp"))


def test_render_command_accepts_injected_engine(tmp_path, capsys):
    workspace = _workspace(tmp_path / "workspace")
    assert render_command.run(
        argparse.Namespace(workspace=str(workspace)),
        engine=lambda _workspace: RenderResult(
            ("one.md",),
            ("two.md",),
            (("unchanged", "two.md"), ("written", "one.md")),
        ),
    ) == 0
    assert capsys.readouterr().out == "unchanged two.md\nwritten one.md\n"


def test_render_records_mixed_actions_in_registry_order(tmp_path):
    workspace = _workspace(tmp_path / "workspace")
    render_workspace(workspace)
    (workspace / ".cursor/rules/apparatus.mdc").unlink()
    result = render_workspace(workspace)
    assert result.actions == (
        ("unchanged", "CLAUDE.md"),
        ("written", ".cursor/rules/apparatus.mdc"),
        ("unchanged", ".github/copilot-instructions.md"),
    )
