"""Markdown rendering and writing for System/machine-report.md."""

from __future__ import annotations

from collections.abc import Callable
from datetime import datetime, timezone
import json
from pathlib import Path
from typing import Any

from apparatus_core import __version__


def utc_now() -> datetime:
    """Return the current UTC time; passed as a collaborator in tests."""
    return datetime.now(timezone.utc)


def _timestamp(value: datetime) -> str:
    return value.astimezone(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _yaml_value(value: Any) -> str:
    """JSON scalars are valid YAML scalars and preserve plain, stable output."""
    return json.dumps(value, ensure_ascii=False)


def render_machine_report(
    detections: dict[str, Any], *, clock: Callable[[], datetime] = utc_now
) -> str:
    """Render parseable YAML frontmatter and a human-readable report body."""
    generated_at = _timestamp(clock())
    git = detections["git"]
    uv = detections["uv"]
    sync = detections["sync_redirection"]
    apps = detections["ai_apps"]
    snapshots = "available" if git["present"] else "unavailable"
    lines = [
        "---",
        f"generated_at: {_yaml_value(generated_at)}",
        "generator: apparatus",
        f"version: {_yaml_value(__version__)}",
        "os:",
        f"  name: {_yaml_value(detections['os']['name'])}",
        f"  version: {_yaml_value(detections['os']['version'])}",
        "python:",
        f"  version: {_yaml_value(detections['python']['version'])}",
        f"  executable: {_yaml_value(detections['python']['executable'])}",
        f"git: {_yaml_value(git['version'] if git['present'] else None)}",
        f"uv: {_yaml_value(uv['version'] if uv['present'] else None)}",
        f"snapshots: {_yaml_value(snapshots)}",
        "detected_ai_apps:",
    ]
    lines.extend(f"  - {_yaml_value(app)}" for app in apps)
    if not apps:
        lines.append("  []")
    lines.extend(
        [
            "sync_redirection:",
            f"  at_risk: {_yaml_value(sync['at_risk'])}",
            f"  reason: {_yaml_value(sync['reason'])}",
            "---",
            "",
            "# Machine report",
            "",
            f"Generated by Apparatus {__version__} at {generated_at}.",
            "",
            f"Operating system: {detections['os']['name']} {detections['os']['version']}.",
            f"Python: {detections['python']['version']} ({detections['python']['executable']}).",
            f"Git: {'available' if git['present'] else 'not found'}"
            + (f" ({git['version']})." if git['version'] else "."),
            f"uv: {'available' if uv['present'] else 'not found'}"
            + (f" ({uv['version']})." if uv['version'] else "."),
            f"Snapshots: {snapshots}.",
            "Detected AI apps: " + (", ".join(apps) if apps else "none found") + ".",
            f"Sync-redirection risk: {'found' if sync['at_risk'] else 'not found'}. {sync['reason']}",
            "",
        ]
    )
    return "\n".join(lines)


def write_machine_report(
    workspace: str | Path,
    detections: dict[str, Any],
    *,
    clock: Callable[[], datetime] = utc_now,
) -> Path:
    """Create System if needed and idempotently replace the machine report."""
    report_path = Path(workspace) / "System" / "machine-report.md"
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(render_machine_report(detections, clock=clock), encoding="utf-8")
    return report_path
