"""Markdown rendering and writing for System/machine-report.md."""

from __future__ import annotations

from collections.abc import Callable
from datetime import datetime, timezone
import json
import os
from pathlib import Path
from typing import Any

from apparatus_core import __version__
from apparatus_core.fs_transactions import WorkspaceAnchor


def utc_now() -> datetime:
    """Return the current UTC time; passed as a collaborator in tests."""
    return datetime.now(timezone.utc)


def _timestamp(value: datetime) -> str:
    return value.astimezone(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _yaml_value(value: Any) -> str:
    """JSON scalars are valid YAML scalars and preserve plain, stable output."""
    return json.dumps(value, ensure_ascii=False)


def render_machine_report(
    detections: dict[str, Any], *, clock: Callable[[], datetime] = utc_now
) -> str:
    """Render parseable YAML frontmatter and a human-readable report body."""
    generated_at = _timestamp(clock())
    git = detections["git"]
    uv = detections["uv"]
    sync = detections["sync_redirection"]
    apps = detections["ai_apps"]
    snapshots = "available" if git["present"] else "unavailable"
    lines = [
        "---",
        f"generated_at: {_yaml_value(generated_at)}",
        "generator: apparatus",
        f"version: {_yaml_value(__version__)}",
        "os:",
        f"  name: {_yaml_value(detections['os']['name'])}",
        f"  version: {_yaml_value(detections['os']['version'])}",
        "python:",
        f"  version: {_yaml_value(detections['python']['version'])}",
        f"  executable: {_yaml_value(detections['python']['executable'])}",
        f"git: {_yaml_value(git['version'] if git['present'] else None)}",
        f"uv: {_yaml_value(uv['version'] if uv['present'] else None)}",
        f"snapshots: {_yaml_value(snapshots)}",
        "detected_ai_apps:",
    ]
    lines.extend(f"  - {_yaml_value(app)}" for app in apps)
    if not apps:
        lines.append("  []")
    lines.extend(
        [
            "sync_redirection:",
            f"  at_risk: {_yaml_value(sync['at_risk'])}",
            f"  reason: {_yaml_value(sync['reason'])}",
            "---",
            "",
            "# Machine report",
            "",
            f"Generated by Apparatus {__version__} at {generated_at}.",
            "",
            f"Operating system: {detections['os']['name']} {detections['os']['version']}.",
            f"Python: {detections['python']['version']} ({detections['python']['executable']}).",
            f"Git: {'available' if git['present'] else 'not found'}"
            + (f" ({git['version']})." if git['version'] else "."),
            f"uv: {'available' if uv['present'] else 'not found'}"
            + (f" ({uv['version']})." if uv['version'] else "."),
            f"Snapshots: {snapshots}.",
            "Detected AI apps: " + (", ".join(apps) if apps else "none found") + ".",
            f"Sync-redirection risk: {'found' if sync['at_risk'] else 'not found'}. {sync['reason']}",
            "",
        ]
    )
    return "\n".join(lines)


def write_machine_report(
    workspace: str | Path,
    detections: dict[str, Any],
    *,
    clock: Callable[[], datetime] = utc_now,
) -> Path:
    """Publish the report through retained workspace and System identities."""
    workspace_path = Path(workspace)
    report_path = workspace_path / "System" / "machine-report.md"
    content = render_machine_report(detections, clock=clock).encode("utf-8")
    created_system = None
    created_report = None
    transaction = None

    with WorkspaceAnchor(workspace_path) as workspace_anchor:
        try:
            if not workspace_anchor.directory_exists("System"):
                created_system = workspace_anchor.create_directory("System")
                if os.name == "nt":
                    # A newly created Win32 directory owner requests DELETE
                    # access. Release that creation-only handle before the
                    # nested anchor opens the same directory without delete
                    # sharing. The workspace anchor still pins the root and an
                    # empty directory is deliberately left on later failure.
                    created_system.close()
                    created_system = None

            # A second anchor retains the exact System directory selected above.
            # Root and System may still be renamed on POSIX, but a later identity
            # check rejects that replacement and cleanup stays descriptor-relative.
            with WorkspaceAnchor(report_path.parent) as system_anchor:
                if system_anchor.entry_exists("machine-report.md"):
                    existing = system_anchor.capture_file("machine-report.md")
                    try:
                        if existing.content == content:
                            if not (
                                workspace_anchor.root_is_current()
                                and system_anchor.matches_owned(existing)
                            ):
                                raise OSError("machine report destination changed")
                            return report_path
                        transaction = system_anchor.replace_if_unchanged(
                            "machine-report.md",
                            existing.identity,
                            existing.content,
                            content,
                        )
                    finally:
                        existing.close()
                    try:
                        if not (
                            workspace_anchor.root_is_current()
                            and system_anchor.root_is_current()
                        ):
                            raise OSError("machine report destination changed")
                        transaction.validate_commit()
                        transaction.commit()
                    except Exception:
                        transaction.rollback()
                        raise
                    finally:
                        transaction.close()
                        transaction = None
                else:
                    created_report = system_anchor.create_file(
                        "machine-report.md", content
                    )
                    if not (
                        workspace_anchor.root_is_current()
                        and system_anchor.matches_owned(created_report)
                    ):
                        raise OSError("machine report destination changed")
            return report_path
        except Exception:
            if transaction is not None:
                try:
                    transaction.rollback()
                except OSError:
                    pass
                transaction.close()
            if created_report is not None:
                try:
                    # The owned System anchor has already closed here only when
                    # normal control left its block. Its retained parent handle is
                    # still sufficient for exact-object cleanup on POSIX, while
                    # Windows deletes through the owned file handle itself.
                    workspace_anchor.unlink_owned(created_report)
                except OSError:
                    pass
                created_report.close()
            if created_system is not None:
                try:
                    workspace_anchor.remove_owned_directory(created_system)
                except OSError:
                    pass
                created_system.close()
            raise
        finally:
            if created_report is not None:
                created_report.close()
            if created_system is not None:
                created_system.close()
