"""Deterministic rendering of workspace instruction shims."""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
from importlib import resources
import os
from pathlib import Path, PurePosixPath, PureWindowsPath
import stat
from string import Template
import tempfile
import unicodedata

from apparatus_core import shims

CANON_PATH = "AGENTS.md"
_WINDOWS_INVALID_COMPONENT_CHARACTERS = frozenset('<>:"|?*')
_WINDOWS_RESERVED_BASENAMES = frozenset(
    ("con", "prn", "aux", "nul", *(f"com{number}" for number in range(1, 10)), *(f"lpt{number}" for number in range(1, 10)))
)


class RenderError(ValueError):
    """A workspace cannot safely be rendered."""


class CanonMissingError(RenderError):
    """The workspace has no canonical instruction file."""


@dataclass(frozen=True)
class RenderedShim:
    """The expected raw bytes for one registered shim."""

    target: str
    content: bytes


@dataclass(frozen=True)
class RenderResult:
    """The changes made by one render run, in registry order."""

    written: tuple[str, ...]
    unchanged: tuple[str, ...]
    actions: tuple[tuple[str, str], ...] = ()


def normalize_target(target: str) -> Path:
    """Return one portable workspace-relative shim target or fail closed."""
    if not isinstance(target, str):
        raise RenderError(f"registered shim path {target!r} is not normalized")
    path = PurePosixPath(target)
    windows_path = PureWindowsPath(target)
    if (
        not target
        or "\\" in target
        or path.is_absolute()
        or bool(windows_path.drive)
        or path.as_posix() != target
        or any(part in {"", ".", ".."} for part in path.parts)
    ):
        raise RenderError(f"registered shim path {target!r} is not normalized")
    for component in path.parts:
        if (
            component.endswith((".", " "))
            or any(ord(character) < 32 or character in _WINDOWS_INVALID_COMPONENT_CHARACTERS for character in component)
            or _is_windows_reserved_component(component)
        ):
            raise RenderError(f"registered shim path {target!r} is not portable")
    return Path(*path.parts)


def _is_windows_reserved_component(component: str) -> bool:
    """Recognize Windows device-name aliases on every supported platform."""
    is_reserved = getattr(PureWindowsPath(component), "is_reserved", None)
    if callable(is_reserved) and is_reserved():
        return True
    basename = component.split(".", 1)[0].casefold()
    return basename in _WINDOWS_RESERVED_BASENAMES


def _portable_path_key(path: Path) -> tuple[str, ...]:
    """Canonicalize components as a portable case-insensitive Unicode path."""
    return tuple(unicodedata.normalize("NFC", component).casefold() for component in path.parts)


def is_reparse_path(path: Path) -> bool:
    """Detect POSIX symlinks and Windows junction/reparse-point paths."""
    try:
        status = os.lstat(path)
    except OSError:
        return False
    return stat.S_ISLNK(status.st_mode) or bool(
        getattr(status, "st_file_attributes", 0) & 0x400
    )


def _header() -> str:
    return "Generated by apparatus render. Do not edit by hand."


def _template(name: str) -> Template:
    try:
        text = resources.files("apparatus_core.shims").joinpath(name).read_text(
            encoding="utf-8"
        )
    except (FileNotFoundError, ModuleNotFoundError) as error:
        raise RenderError(f"shim template {name!r} could not be read") from error
    return Template(text)


def _validate_registry_targets(targets: tuple[Path, ...]) -> None:
    """Reject conflicting shim destinations before rendering can mutate them."""
    seen: set[tuple[str, ...]] = set()
    canon_key = _portable_path_key(Path(CANON_PATH))
    keyed_targets = tuple((target, _portable_path_key(target)) for target in targets)
    for target, key in keyed_targets:
        if key == canon_key:
            raise RenderError(f"registered shim path {target.as_posix()!r} must not replace {CANON_PATH}")
        if key in seen:
            raise RenderError(f"registered shim path {target.as_posix()!r} is duplicated")
        seen.add(key)
    for index, (_target, key) in enumerate(keyed_targets):
        for _other, other_key in keyed_targets[index + 1 :]:
            if key[: len(other_key)] == other_key or other_key[: len(key)] == key:
                raise RenderError(
                    "registered shim paths must not be ancestors or descendants of each other"
                )


def rendered_shims(
    workspace: str | Path,
    *,
    registry: tuple[tuple[str, str], ...] | None = None,
) -> tuple[RenderedShim, ...]:
    """Render every registered shim in memory from raw canon bytes."""
    root = Path(workspace)
    if is_reparse_path(root):
        raise RenderError("workspace path '.' must not be a symbolic link")
    canon = root / CANON_PATH
    if is_reparse_path(canon):
        raise RenderError(f"workspace path {CANON_PATH!r} must not be a symbolic link")
    if not canon.is_file():
        raise CanonMissingError(f"workspace is missing {CANON_PATH}; create it before rendering shims")
    try:
        canon_bytes = canon.read_bytes()
    except OSError as error:
        raise RenderError(f"could not read {CANON_PATH}") from error
    return rendered_shims_from_bytes(canon_bytes, registry=registry)


def rendered_shims_from_bytes(
    canon_bytes: bytes,
    *,
    registry: tuple[tuple[str, str], ...] | None = None,
) -> tuple[RenderedShim, ...]:
    """Render from an already captured canon, without another filesystem read."""
    digest = hashlib.sha256(canon_bytes).hexdigest()
    active_registry = shims.SHIM_REGISTRY if registry is None else registry
    entries: list[tuple[Path, str]] = []
    for target, template_name in active_registry:
        normalized = normalize_target(target)
        entries.append((normalized, template_name))
    _validate_registry_targets(tuple(target for target, _template_name in entries))

    rendered: list[RenderedShim] = []
    for normalized, template_name in entries:
        template = _template(template_name)
        content = template.substitute(
            header=_header(),
            canon_path=CANON_PATH,
            canon_digest=digest,
        ).encode("utf-8")
        rendered.append(RenderedShim(normalized.as_posix(), content))
    return tuple(rendered)


def _preflight_target(root: Path, target: str) -> Path:
    """Reject unsafe target components without creating or writing anything."""
    relative = normalize_target(target)
    current = root
    for index, part in enumerate(relative.parts):
        current /= part
        display = Path(*relative.parts[: index + 1]).as_posix()
        if is_reparse_path(current):
            raise RenderError(f"workspace path {display!r} must not be a symbolic link")
        if index < len(relative.parts) - 1:
            if current.exists() and not current.is_dir():
                raise RenderError(f"workspace path {display!r} must be a directory")
    if current.exists() and not current.is_file():
        raise RenderError(f"workspace path {relative.as_posix()!r} must be a file")
    return current


def render_workspace(
    workspace: str | Path,
    *,
    registry: tuple[tuple[str, str], ...] | None = None,
) -> RenderResult:
    """Write registered shims only when their expected bytes differ."""
    root = Path(workspace)
    if is_reparse_path(root):
        raise RenderError("workspace path '.' must not be a symbolic link")
    rendered = rendered_shims(root, registry=registry)
    targets = tuple((shim, _preflight_target(root, shim.target)) for shim in rendered)
    written: list[str] = []
    unchanged: list[str] = []
    actions: list[tuple[str, str]] = []
    for shim, target in targets:
        try:
            target.parent.mkdir(parents=True, exist_ok=True)
            existing = target.read_bytes() if target.is_file() else None
            if existing == shim.content:
                unchanged.append(shim.target)
                actions.append(("unchanged", shim.target))
                continue
            _replace_target(target, shim.content)
        except OSError as error:
            raise RenderError(f"could not write shim {shim.target!r}") from error
        written.append(shim.target)
        actions.append(("written", shim.target))
    return RenderResult(tuple(written), tuple(unchanged), tuple(actions))


def _replace_target(target: Path, content: bytes) -> None:
    """Publish one shim without modifying an existing target inode in place."""
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=".apparatus-render-", suffix=".tmp", dir=target.parent
    )
    temporary = Path(temporary_name)
    identity: tuple[int, int] | None = None
    try:
        temporary_status = os.fstat(descriptor)
        identity = (temporary_status.st_dev, temporary_status.st_ino)
        output = os.fdopen(descriptor, "wb")
        descriptor = -1
        with output:
            output.write(content)
            output.flush()
        if not _temporary_matches(temporary, identity, content):
            raise OSError("renderer temporary changed before replacement")
        os.replace(temporary, target)
    except OSError as error:
        if descriptor >= 0:
            try:
                os.close(descriptor)
            except OSError:
                pass
        _remove_owned_temporary(temporary, identity, content)
        raise RenderError(f"could not write shim {target.name!r}") from error


def _remove_owned_temporary(
    temporary: Path,
    identity: tuple[int, int] | None,
    content: bytes,
) -> None:
    """Remove only a still-owned renderer temporary after a failed replacement."""
    if identity is None:
        return
    try:
        status = os.lstat(temporary)
        if (
            stat.S_ISREG(status.st_mode)
            and (status.st_dev, status.st_ino) == identity
            and temporary.read_bytes() == content
        ):
            temporary.unlink()
    except OSError:
        return


def _temporary_matches(
    temporary: Path,
    identity: tuple[int, int],
    content: bytes,
) -> bool:
    """Confirm the pathname still names our closed temporary before publishing."""
    try:
        status = os.lstat(temporary)
        return (
            stat.S_ISREG(status.st_mode)
            and (status.st_dev, status.st_ino) == identity
            and temporary.read_bytes() == content
        )
    except OSError:
        return False
